### ISSUE TITLE
[BROKEN LINK] O3DE Learn at the top-left corner

### ISSUE THREAD

**Issue by chanmosq** [o3de/o3de.org#1166]
## Which page has the broken link?

Clicking on O3DE Learn should take you to the o3de.org/docs landing page (with the tiles). Not to o3de.org website.

Steps to reproduce problem: 
1. Go to any page in the O3DE Documentation. For example: https://o3de.org/docs/welcome-guide/
2. Click on O3DE Learn in the top left corner. 
![2021-11-11_16-38-34](https://user-images.githubusercontent.com/75444793/141389106-5675a963-bbf5-4a32-adcb-3c6ca13205e9.png)
3. Notice the logo is called "O3DE Learn", but it takes you to the home page, not the documentation page. 

## Which link was broken?

The "O3DE Learn" logo at the top-left corner of every page in the docs. 

## Know where it should go?

https://o3de.org/docs/

**Comment by AMZN-daimini** [comment]
I agree, but if we did that then there would be no way to go back to the "main site".
I'm not sure if I like the suggestion of putting it in the hamburger menu (https://github.com/o3de/o3de.org/issues/1167) since it's so much harder to discover. Maybe we could have some other icon in the top bar that can be linked to the main site? Or maybe "O3DE" could link to the main homepage, and "LEARN" could link to the docs homepage? (though I can see that being confusing too)

**Comment by chanmosq** [comment]
Adding @amzn-leenguy, who requested the ticket and may have additional thoughts?

@AMZN-daimini, those are both good points. What if we did a layout similar to Microsoft's header (see image below). Its following features address both of our problems:
1. The main logo goes back to the Microsoft home page. 
2. The **Docs** button goes to the the home page for documentation. 
3. The divider (`|`) between **Microsoft** and **Docs** is a visual cue that they link to different places, and aren't one word. We can have a similar divider or adequate spacing.  

![image](https://user-images.githubusercontent.com/75444793/141845927-1508e405-39de-4919-989c-d6a74cd1155f.png)

**Comment by amzn-leenguy** [comment]
@chanmosq and @AMZN-daimini . After some UX Research with all our participants, 6 of 6 people expected that clicking on the logo would take them back to O3de.org/docs

Another suggestion that @bhanuja-s suggested after some research on her side as well, was instead of having the Back to O3DE.org in the hamburger menu, we could add a home icon to the top nav to signify that links to o3de.org. I'm not sure if a home icon is clear enough, but I still feel like if users have clicked into the O3DE.org Learn website, they most likely want to stay there and explore the content there. Rather then giving any obvious options go back to o3de.org. Since most of the content on there are for marketing purposes.

In regards to your suggestion that Microsoft is doing, I'm not sure I can fully agree to that suggestion, since Microsoft has a lot of interactive things that a user can do that is contextual to their content main website. Right now our o3de.org website only has so much content you can digest, that it wraps up pretty quickly. 

I would still like to stick with the data we have found from our UXR sessions and update o3de.org learn logo to go back to the o3de.org/learn home page.

And if a user needs to go back to the o3de.org website, they are still able to get there via the footer logo, or the optional link in the hamburger (if we can make that happen) or just edit the URL address.

I know this sounds like a odd solution, but I want to stick with expectations that all 100% of our participants gave us. 

Also this website has some great references as well for docs hierarchy too: https://stripe.com/docs

**Comment by chanmosq** [comment]
We had a discussion with SIG UI UX here: https://discord.com/channels/805939474655346758/816043761687068712/910612262526545920

To resolve this issue, I believe we can move forward with changing the **O3DE Learn** button to go to o3de.org/docs page. 

The missing home page button that arises is a major issue, but not critical to resolve this O3DE Learn issue. There's an existing feature request to add a home page button here: https://github.com/o3de/o3de.org/issues/1167. However, sig-ui-ux did not come to a clear decision on how to address it at this time. 

For now, users can go back to the home page by entering the address in their browser or by clicking the logo at the bottom of each page.

**Comment by amzn-leenguy** [comment]
Has this issue been addressed yet?

**Comment by chanmosq** [comment]
Looks like it hasn't, thanks for boosting this. I'll take a look at it!

**Comment by chanmosq** [comment]
@amzn-leenguy @AMZN-daimini  I created a PR to resolve this issue, please review it [here](https://github.com/o3de/o3de.org/pull/1412). 

The "O3DE Learn" logo should redirect you to the o3de.org/docs page. This fix does not prevent users from going back to the home o3de.org page, because users can click the "O3DE" logo at the bottom of any page to do that.
