### ISSUE TITLE
Console Variable Tutorial page is blank

### ISSUE THREAD

**Issue by allisaurus** [o3de/o3de.org#1441]
## Describe the issue

CVAR tutorial doesn't exist, but is linked to from the "Programming" user guide.

## Impacted page(s)

https://www.o3de.org/docs/user-guide/programming/cvars/

## Expected experience

That this page would contain guidance on using console variables with O3DE.

**Comment by sptramer** [comment]
Need to create a related ticket to _write_ a CVAR usage/setup tutorial.

**Comment by chanmosq** [comment]
We have one already here: https://www.o3de.org/docs/user-guide/programming/az-console/#console-variables-cvars
This issue does highlight a problem we have with unorganized CVAR documentation, and is only one task in a greater plan to audit CVAR docs.

**Comment by chanmosq** [comment]
Removing this page because it's empty and the need for it is outdated. (PR: https://github.com/o3de/o3de.org/pull/2228)There's a page about CVARs here: https://www.o3de.org/docs/user-guide/appendix/cvars/

And there are more specific issues more info about CVARs here: https://github.com/o3de/o3de.org/issues/1634 https://github.com/o3de/o3de.org/issues/1554 https://github.com/o3de/o3de.org/issues/1657
