### ISSUE TITLE
[DOCS] Document how to interact with entities

### ISSUE THREAD

**Issue by FiniteStateGit** [o3de/o3de.org#1562]
## Describe the issue briefly

Create content for a drafted page.

Page metadata:
title: Entities
draft: true

## Which page(s) / section(s) are affected?

content\docs\user-guide\interactivity\entities\_index.md

**Comment by sptramer** [comment]
* Navigate entity hierarchies
* Gameplay bus information

Originally intended as complete coverage of how to use entities. A lot of the entity stuff has been moved around the guide a bit, and there is a tutorial in progress for how to work with entities and prefabs.

**Comment by chanmosq** [comment]
There are is a tutorial that covers this now: [Entity and Prefab Basics](https://www.o3de.org/docs/learning-guide/tutorials/entities-and-prefabs/) - About how to create, rename, edit, save, and various other ways to interact with entities and prefabs in O3DE Editor

Because this empty page (interactivity/entities/_index.md) was created as a placeholder for information, which was later placed in another location in the docs, then there is currently no longer plans to do anything with this section. If in the future, content is planned for this section, then we can decide then to recreate this section and fill it with content. For now, I think it's safe to remove this page. 

Linking a PR to remove this page: https://github.com/o3de/o3de.org/pull/2226
