### ISSUE TITLE
[Incomplete Information]: Configure and Build: Command line guide lacks specific information

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#168]
Link: https://o3deorg.netlify.app/docs/user-guide/build/configure-and-build/

"Configure with the CMake CLI" section contains unspecified commands - problems with execution of the command begins at "cmake -B windows_vs2019 -S ." where it is unclear which directory is required. It's not possible to complete the "Configure with the CMake CLI" prevents the sections "Build your project" and "Build the O3DE editor, engine, and tools" from being checked as well.

**Comment by willihay** [comment]
The instructions referred to in this issue have been iterated upon a few times since the issue was filed. In its current state, I believe we are much more clear about the project directory. For example, we now demonstrate how to configure and build using a real directory name, "C:\o3de-projects\MyProject".

The new link is: https://www.o3de.org/docs/welcome-guide/create/creating-projects-using-cli/creating-windows/
