### ISSUE TITLE
[DOCS] Fix overview.md / _index.md issues

### ISSUE THREAD

**Issue by sptramer** [o3de/o3de.org#1685]
## Describe the issue briefly

Currently there are a number of `overview.md` pages, which were created to handle some website issues where the left-hand ToC expansion causes a title repeat, which didn't clearly indicate that the first entry in the index should be an overview:

![image](https://user-images.githubusercontent.com/169061/171909994-c0a05d2e-6861-4d3d-962a-3b8207418dd1.png)

This also leads to situations in which the root topic URL (i.e. `docs/user-guide/gems`) is an empty page with no guidance, where the root overview is located at `docs/user-guide/gems/overview`.

In response, we received PR #1495, which adds the `sectionPageTitle` metadata field, allowing for `_index.md` files to have a different title representation in the ToC tree as a section title and a page title:

![image](https://user-images.githubusercontent.com/169061/171910251-5dce0949-b3c8-4ef6-9c27-c97cc1d7500f.png)

This issue is for performing a consistency update to the docs in order to:

* Migrate content from any `overview.md` files into `_index.md` files
* Configure redirects from `<topic>/overview` to `<topic>`
* Appropriately show `_index.md` pages as `Overview` in the expanded ToC tree

## Which page(s) / section(s) are affected?

Most `_index.md` files are affected as they do not contain the `sectionPageTitle` metadata. Grep:

```
grep -rlv sectionPageTitle content | grep '_index.md'
```

There are also a number of `overview.md` files:

```
find content -name overview.md 
``` 

## Does this work have an engineering dependency? What is it?

No.

**Comment by chanmosq** [comment]
We'll need to pivot the solution for this issue, since https://github.com/o3de/o3de.org/pull/1859 introduces fixes to the left navigation in the website. Now, in the left navigation, the section title and the first page (_index.md) are no longer listed as separate links. Only the section title appears, and clicking on it links to the corresponding _index.md page. In _index.md, `linkTitle` remains to be the title shown in the left nav, and `title` remains to be the H1 header when the page is opened. 

The updated solution for this issue is
- Migrate content from any overview.md files into _index.md files
- Configure redirects from <topic>/overview to <topic>
- Undo the changes in https://github.com/o3de/o3de.org/pull/1495 and remove any instance of `sectionPageTitle`.
