### ISSUE TITLE
[ISSUE][DOCS] Numbers in the ordered lists in Tools UI Component Library don't increment

### ISSUE THREAD

**Issue by willihay** [o3de/o3de.org#836]
## Describe the issue

The numbers in the ordered lists in various pages of the Tools UI Component Library do not increment. They remain at "1."

## Impacted page(s)

Examples include:

https://o3de.org/docs/tools-ui/component-library/uidev-browse-edit-component/#anatomy-of-the-browse-edit-widgeta-namebrowse-edit-anatomya

https://o3de.org/docs/tools-ui/component-library/uidev-button-component/#usage-guidelinesa-namebutton-usagea

(Also, the section links are a weird combination of formatting.)

## Expected experience

Ordered lists that increment properly.

**Comment by Shyamalsian** [comment]
Hi I am Shyamal Kumar Gupta an UnderGraduate Student persuing IT .
I have a knowledge of HTML CSS and a bit of JavaScript .
So can I try to fix this issue.

**Comment by FiniteStateGit** [comment]
@willihay Can this issue be closed now?

**Comment by Shyamalsian** [comment]
I wanted to contribute but due to some confusion I am not getting the
correct process.
I have changed the things in a new commit and mentioned the previous commit
reference in the new commit but I don't know what is required to be done.
I have asked for the discord link ,if some guidance is provided it may help
me to learn something new and fix the issue.
