### ISSUE TITLE
get_python.bat behavior in git-bash not documented

### ISSUE THREAD

**Issue by LincePotiguara** [o3de/o3de.org#948]
**Describe the bug**
Running `python\get_python` after compilation sets up the python runtime only to the terminal the command was typed in.

**To Reproduce**
1. Follow the required building steps, except step 3
2. Delete or rename python\runtime folder if it exists
3. Run python\get_python.bat
4. Open a new terminal
5. Run Editor.exe through the terminal
6. See error

**Expected behavior**
The configuring process should not be local to the terminal.

**Screenshots**
![error](https://user-images.githubusercontent.com/12141500/124834379-093b6100-df56-11eb-986d-49060e1f9992.PNG)

**Additional context**
It's possible to run Editor.exe normally only after the execution of the batch file, but running Editor.exe from a new terminal or from the Explorer yields the same error.

**Comment by willihay** [comment]
Install documentation - both in the readme and on the website - has been iterated upon and improved since this issue was filed. This should address the original issue.

I am unable to repro the issue that @nakhleh experienced with the git bash shell. I was successfully able to register an engine using both o3de.sh and o3de.bat from a git bash window. I noticed that several improvements were made to this script around the same time this issue was filed. It is possible that one of these fixed the issue that was reported here. Please file a new GitHub issue in the o3de.org docs repo  (https://github.com/o3de/o3de.org/issues) if the problem can be reproduced with a more recent version of the engine.
